### ISSUE TITLE
 need fix LoadLfsConfig

### ISSUE THREAD

**Issue by kane9527-e** [mikerochip/unity-git-tools#9]
<img width="505" alt="image" src="https://github.com/mikerochip/unity-git-tools/assets/9569527/1c2abe0a-f231-4003-939e-afc4a3f08d88">
 
private void LoadLfsConfig()
        {
            _hasLfsConfig = false;
            
            if (!IsGitRepo)
                return;
            
            var configPath = Path.Combine(_repoRootPath, ".git", "config");
            if (!File.Exists(configPath))
                throw new Exception($"[Git] Failed to load Git config \"{configPath}\"");

            var text = File.ReadAllText(configPath);
            _hasLfsConfig = text.Contains("[lfs]");//change ->  _hasLfsConfig = text.Contains("[lfs")
        }

**Comment by mikerochip** [comment]
hi @kane9527-e, I can fix this, but could you tell me what `git-lfs` version you're using? This looks like an older format.

My version is like this
```
mike@mikes-mbp14 ~ % git-lfs version
git-lfs/3.3.0 (GitHub; darwin arm64; go 1.19.3)
```

**Comment by kane9527-e** [comment]
TortoiseGit 2.14.0.0 (Hotfix 2.14.0.1; C:\Program Files\TortoiseGit\bin)
git version 2.34.1.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\etc\gitconfig)> 
![image](https://github.com/mikerochip/unity-git-tools/assets/9569527/f8b26554-1fec-4852-a7b7-b76232e47f71)
